[theme]
primaryColor="#FF4B4B"       # Streamlit Red
backgroundColor="#FFFFFF"     # White background
secondaryBackgroundColor="#F0F2F6" # Light grey for elements
textColor="#31333F"           # Default text color
font="sans serif"

[server]
headless = true # Recommended for deployments
enableCORS = false # Usually handled by Streamlit Community Cloud proxy

[client]
showSidebarNavigation = true # Enable sidebar nav for multi-page apps
